### ISSUE TITLE
The plugin "gatsby-source-directus" created a node of a type "File" owned by "gatsby-source-filesystem"

### ISSUE THREAD

**Issue by mannp** [directus/gatsby-source-directus#25]
Gatsby 5.9 and 5.10, Directus 10.2.1, gatsby-source-filesystem 5.10, @directus/gatsby-source-directus 9.15.1

Highlighting the same issue that has been reported by strapi users has affected me using gatsby-source-directus too.

Added as a placeholder while tracking https://github.com/gatsby-uc/plugins/issues/426#issuecomment-1562455390%E2%80%A6

Reverting to gatsby 5.8 and gatsby-source-filesystem 5.8 things work again.

**Comment by cdanny358** [comment]
Experiencing the same issue, except in my case it will work with the latest version of Gatsby (5.10.0 as of this post) if I use gatsby-source-directus 9.15.0 rather than 9.15.1, **AND** always run `yarn clean` before `yarn start` or `yarn build`. Always get the error above when running gatsby-source-directus 9.15.1, or when not cleaning first.

**Comment by rijkvanzanten** [comment]
@mannp From the linked issue, it looks like the Gatsby team is working on a fix for Gatsby? 🤔 

PRs more than welcome if there's a proposed fix for within the Directus abstraction itself 🙂

**Comment by mannp** [comment]
@rijkvanzanten that is my understanding yes, so I am hopeful the issue will get fixed there. This was more a placeholder and to acknowledge the issue for directus too.

**Comment by rijkvanzanten** [comment]
Gotcha! Thanks for confirming

**Comment by LekoArts** [comment]
We're tracking this here and you can try a new version: https://github.com/gatsbyjs/gatsby/issues/38117#issuecomment-1592719231

**Comment by mannp** [comment]
> We're tracking this here and you can try a canary: [gatsbyjs/gatsby#38117 (comment)](https://github.com/gatsbyjs/gatsby/issues/38117#issuecomment-1592092933)

Thanks 👍🏻 

@rijkvanzanten does this response from @LekoArts make sense to you in the context of directus?

https://github.com/gatsbyjs/gatsby/issues/38117#issuecomment-1592653058

**Comment by mannp** [comment]
> We're tracking this here and you can try a new version: [gatsbyjs/gatsby#38117 (comment)](https://github.com/gatsbyjs/gatsby/issues/38117#issuecomment-1592719231)

Resolved for me thank you @LekoArts

**Comment by rijkvanzanten** [comment]
@mannp I don't really know enough about Gatsby or how their plugins work to comment on this I'm afraid..
